### ISSUE TITLE
[Bug Report/Feeback] @fesjs/builder-vite build失败 似乎未读取项目`tsconfig.json`

### ISSUE THREAD

**Issue by NexZhu** [WeBankFinTech/fes.js#125]
**问题描述**

`npm run build`报错`Element Plus`源码中import `dayjs`，提示找不到default export
推测builder-vite在TypeScript项目中`tsconfig.json` `"allowSyntheticDefaultImports": true` 未生效
正常开启该选项即使没有default export也能使用如下写法：
```ts
import dayjs from 'dayjs'
```

**环境描述/版本信息 (请完成如下信息)**
 - OS: Windows
 - Node: v16.12.0
 - fes -V: 3.0.0-beta.3
 - @fesjs/builder-vite: 3.0.0-beta.5
 - 项目package.json
https://github.com/daotl/fes-starter/blob/feat/fes-v3-vite/package.json

**如何复现**
复现步骤
1. npm install
2. npm run build

**预期结果**
简明扼要的说明你期待的结果

build成功

**日志**

![image](https://user-images.githubusercontent.com/4370605/169196639-c60de690-03c3-4555-8f31-1c28fe0790ba.png)

```
> @daotl/fes-starter@3.0.0 build
> cross-env RM_TMPDIR=none fes build

vite v2.9.9 building for production...                                                                 11:05:32
transforming (188) src\config\loader.ts
 ERROR  [BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.

✓ 13359 modules transformed.                                                                           11:06:16  

 ERROR  'default' is not exported by node_modules/.pnpm/dayjs@1.11.1/node_modules/dayjs/dayjs.min.js, imported by node_modules/.pnpm/element-plus@2.2.0_vue@3.2.33/node_modules/element-plus/es/components/time-picker/src/common/picker2.mjs
file: C:/0/dev/daotl/web/fes-starter/node_modules/.pnpm/element-plus@2.2.0_vue@3.2.33/node_modules/element-plus/es/components/time-picker/src/common/picker2.mjs:2:7
1: import { defineComponent, inject, ref, watch, nextTick, computed, unref, provide, resolveComponent, openBlock, createBlock, mergeProps, withCtx, normalizeClass, normalizeStyle, withModifiers, resolveDynamicComponent, createCommentVNode, createElementBlock, createElementVNode, renderSlot, toDisplayString } from 'vue';
2: import dayjs from 'dayjs';
          ^
3: import { isEqual } from 'lodash-unified';
4: import { onClickOutside } from '@vueuse/core';


 ERROR  'default' is not exported by node_modules/.pnpm/dayjs@1.11.1/node_modules/dayjs/dayjs.min.js, imported by node_modules/.pnpm/element-plus@2.2.0_vue@3.2.33/node_modules/element-plus/es/components/time-picker/src/common/picker2.mjs


 ERROR  Error: 'default' is not exported by node_modules/.pnpm/dayjs@1.11.1/node_modules/dayjs/dayjs.min.js, imported by node_modules/.pnpm/element-plus@2.2.0_vue@3.2.33/node_modules/element-plus/es/components/time-picker/src/common/picker2.mjs
    at error (C:\0\dev\daotl\web\fes-starter\node_modules\.pnpm\rollup@2.73.0\node_modules\rollup\dist\shared\rollup.js:198:30)
    at Module.error (C:\0\dev\daotl\web\fes-starter\node_modules\.pnpm\rollup@2.73.0\node_modules\rollup\dist\shared\rollup.js:12555:16)
    at Module.traceVariable (C:\0\dev\daotl\web\fes-starter\node_modules\.pnpm\rollup@2.73.0\node_modules\rollup\dist\shared\rollup.js:12914:29)
    at ModuleScope.findVariable (C:\0\dev\daotl\web\fes-starter\node_modules\.pnpm\rollup@2.73.0\node_modules\rollup\dist\shared\rollup.js:11543:39)
    at FunctionScope.findVariable (C:\0\dev\daotl\web\fes-starter\node_modules\.pnpm\rollup@2.73.0\node_modules\rollup\dist\shared\rollup.js:6517:38)
    at ChildScope.findVariable (C:\0\dev\daotl\web\fes-starter\node_modules\.pnpm\rollup@2.73.0\node_modules\rollup\dist\shared\rollup.js:6517:38)
    at Identifier.bind (C:\0\dev\daotl\web\fes-starter\node_modules\.pnpm\rollup@2.73.0\node_modules\rollup\dist\shared\rollup.js:7577:40)
    at CallExpression.bind (C:\0\dev\daotl\web\fes-starter\node_modules\.pnpm\rollup@2.73.0\node_modules\rollup\dist\shared\rollup.js:5361:23)
    at CallExpression.bind (C:\0\dev\daotl\web\fes-starter\node_modules\.pnpm\rollup@2.73.0\node_modules\rollup\dist\shared\rollup.js:8984:15)
    at MemberExpression.bind (C:\0\dev\daotl\web\fes-starter\node_modules\.pnpm\rollup@2.73.0\node_modules\rollup\dist\shared\rollup.js:5361:23)
```

**Comment by wanchun** [comment]
添加配置即可：
```js
alias: {
    dayjs: 'dayjs/esm/index.js'
},
```

本质上这是dayjs的bug，在package.json中未配置module入口，导致只能加载cjs的dayjs.min.js

**Comment by NexZhu** [comment]
请问为什么不用Fes.js，直接用vite的项目中不会出现这个问题呢

**Comment by NexZhu** [comment]
另外尝试了在使用`builder-vite`时添加alias
```
  alias: {
    '~': '/src',
    dayjs: 'dayjs/esm/index.js',
  }
```
Vite会去项目根目录下寻找`dayjs/esm/index.js`文件，写成这样才有效
```
  alias: {
    '~': '/src',
    dayjs: 'node_modules/dayjs/esm/index.js',
  }
```
