### ISSUE TITLE
fes-template-vite pnpm dev报SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by ArtisanQ** [WeBankFinTech/fes.js#210]
> fes dev

Unexpected token 'export'
C:\Users\cq\Desktop\fes.js-master\fes.js-master\packages\fes\lib\index.js:1
export * from '@@/core/coreExports';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Module._compile (C:\Users\cq\Desktop\fes.js-master\fes.js-master\node_modules\.pnpm\pirates@4.0.5\node_modules\pirates\lib\index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at newLoader (C:\Users\cq\Desktop\fes.js-master\fes.js-master\node_modules\.pnpm\pirates@4.0.5\node_modules\pirates\lib\index.js:141:7)
    at Object.newLoader [as .js] (C:\Users\cq\Desktop\fes.js-master\fes.js-master\node_modules\.pnpm\pirates@4.0.5\node_modules\pirates\lib\index.js:141:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)

**Comment by wanchun** [comment]
这样看不出问题，可以把demo上传到git，然后发来git地址

**Comment by neostfox** [comment]
npm run bootstarp 之后，cd packages/fes-template-vite 执行pnpm run dev，就会报上述错误。 windows x64
